version: '3.9'

services:
  # auth-service:
  #   container_name: eventx-auth-service

  #   build:
  #     context: .
  #     dockerfile: ./apps/auth-service/Dockerfile
  #   # target: production
  #   # command: npm run serve:auth-service
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./apps/auth-service/.env
  #   environment:
  #     - DATABASE_HOST=db-core
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./volumes/rabbitmq/data/:/var/lib/rabbitmq/
      - ./volumes/rabbitmq/log/:/var/log/rabbitmq

  db-core:
    image: mongo:4.4.6
    container_name: 'eventx-core-mongodb'
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=bookstore
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./volumes/mongodb:/data/db
    ports:
      - 27017:27017
